/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tutuionmediapleaseletitbefinal;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author blank
 */
public class Stats extends javax.swing.JFrame {

    /**
     * Creates new form Stats
     */
    
    
    
    
    public Stats() {
        initComponents();
        total_count();
    }
    
    
    public void total_count(){
        
        int a = 0, b = 0;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=TuitionMedia100;selectMethod=cursor", "sa", "123456");
            
            
            Statement statement = connection.createStatement();
            
            ResultSet resultSet2 = statement.executeQuery("select count(t_ID) as Counter from TEACHER ");
                while (resultSet2.next()) {
                    String Bid = resultSet2.getString("Counter"); 
                    a=Integer.parseInt(Bid);
                    textfield_total_tutors.setText(Bid);
                }
                
            ResultSet resultSet3 = statement.executeQuery("select count(s_ID) as Counter from STUDENT ");
                while (resultSet3.next()) {
                    String Bid = resultSet3.getString("Counter"); 
                    b=Integer.parseInt(Bid);
                    textfield_total_students.setText(Bid);
                }
                
            ResultSet resultSet4 = statement.executeQuery("select count(s_ID) as Counter from ONGOING_TUITION ");
                while (resultSet4.next()) {
                    String Bid = resultSet4.getString("Counter"); 
                    b=Integer.parseInt(Bid);
                    jTextField_Ongoing.setText(Bid);
                }
            
            ResultSet resultSet5 = statement.executeQuery("select count(serial) as Counter from APPLIED_TUITION ");
                while (resultSet5.next()) {
                    String Bid = resultSet5.getString("Counter"); 
                    b=Integer.parseInt(Bid);
                    textfield_applied_tuition.setText(Bid);
                }
                
            ResultSet resultSet6 = statement.executeQuery("select count(serial) as Counter from REQUESTED_TUTION ");
                while (resultSet6.next()) {
                    String Bid = resultSet6.getString("Counter"); 
                    b=Integer.parseInt(Bid);
                    textfield_requested_tution.setText(Bid);
                }
                
            ResultSet resultSet7 = statement.executeQuery("select count(serial) as Counter from BLACKLIST ");
            while (resultSet7.next()) {
            String Bid = resultSet7.getString("Counter"); 
            b=Integer.parseInt(Bid);
            textfield_blacklist.setText(Bid);
            }
                
                
            
        }catch(Exception e){
        
        System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textfield_total_tutors = new javax.swing.JTextField();
        textfield_total_students = new javax.swing.JTextField();
        jTextField_Ongoing = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textfield_applied_tuition = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textfield_requested_tution = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textfield_blacklist = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_Reject1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(74, 31, 61));

        jLabel1.setBackground(new java.awt.Color(74, 31, 61));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 23)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total Students :");

        jLabel3.setBackground(new java.awt.Color(74, 31, 61));
        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 23)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ongoing Tutions :");

        textfield_total_tutors.setEditable(false);
        textfield_total_tutors.setBackground(new java.awt.Color(74, 31, 61));
        textfield_total_tutors.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        textfield_total_tutors.setForeground(new java.awt.Color(255, 255, 255));
        textfield_total_tutors.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textfield_total_tutors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_total_tutorsActionPerformed(evt);
            }
        });

        textfield_total_students.setEditable(false);
        textfield_total_students.setBackground(new java.awt.Color(74, 31, 61));
        textfield_total_students.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        textfield_total_students.setForeground(new java.awt.Color(255, 255, 255));
        textfield_total_students.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField_Ongoing.setEditable(false);
        jTextField_Ongoing.setBackground(new java.awt.Color(74, 31, 61));
        jTextField_Ongoing.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jTextField_Ongoing.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Ongoing.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setBackground(new java.awt.Color(74, 31, 61));
        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 23)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Applied :");

        textfield_applied_tuition.setEditable(false);
        textfield_applied_tuition.setBackground(new java.awt.Color(74, 31, 61));
        textfield_applied_tuition.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        textfield_applied_tuition.setForeground(new java.awt.Color(255, 255, 255));
        textfield_applied_tuition.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textfield_applied_tuition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_applied_tuitionActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(74, 31, 61));
        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 23)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Requested :");

        textfield_requested_tution.setEditable(false);
        textfield_requested_tution.setBackground(new java.awt.Color(74, 31, 61));
        textfield_requested_tution.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        textfield_requested_tution.setForeground(new java.awt.Color(255, 255, 255));
        textfield_requested_tution.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textfield_requested_tution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_requested_tutionActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(74, 31, 61));
        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 23)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Blacklisted :");

        textfield_blacklist.setEditable(false);
        textfield_blacklist.setBackground(new java.awt.Color(74, 31, 61));
        textfield_blacklist.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        textfield_blacklist.setForeground(new java.awt.Color(255, 255, 255));
        textfield_blacklist.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textfield_blacklist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_blacklistActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(74, 31, 61));

        jLabel7.setBackground(new java.awt.Color(74, 31, 61));
        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 32)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Stats");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );

        jLabel2.setBackground(new java.awt.Color(74, 31, 61));
        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 23)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Total Tutors :");

        jButton_Reject1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_Reject1.setText("Back");
        jButton_Reject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Reject1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(textfield_total_tutors)
                    .addComponent(textfield_applied_tuition, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_Reject1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfield_requested_tution)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(textfield_total_students))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jTextField_Ongoing)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textfield_blacklist))
                        .addGap(62, 62, 62))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_total_tutors, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_total_students, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Ongoing, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_applied_tuition, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_requested_tution, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_blacklist, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton_Reject1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfield_applied_tuitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_applied_tuitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_applied_tuitionActionPerformed

    private void textfield_requested_tutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_requested_tutionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_requested_tutionActionPerformed

    private void textfield_blacklistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_blacklistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_blacklistActionPerformed

    private void textfield_total_tutorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_total_tutorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_total_tutorsActionPerformed

    private void jButton_Reject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Reject1ActionPerformed
        // TODO add your handling code here:
        AdminPanal adminPanal = new AdminPanal();
        adminPanal.show();
        dispose();

    }//GEN-LAST:event_jButton_Reject1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Reject1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField_Ongoing;
    private javax.swing.JTextField textfield_applied_tuition;
    private javax.swing.JTextField textfield_blacklist;
    private javax.swing.JTextField textfield_requested_tution;
    private javax.swing.JTextField textfield_total_students;
    private javax.swing.JTextField textfield_total_tutors;
    // End of variables declaration//GEN-END:variables
}
