/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tutuionmediapleaseletitbefinal;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author blank
 */
public class StudentAfterLoginForm extends javax.swing.JFrame {

    /**
     * Creates new form StudentAfterLoginForm
     */
    public StudentAfterLoginForm() {
        initComponents();
        show_teachers();
        
        Tutor_Table.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,12));
        Tutor_Table.getTableHeader().setOpaque(false);
        Tutor_Table.getTableHeader().setBackground(new Color(32, 136, 203));
        Tutor_Table.getTableHeader().setForeground(new Color(255,255,255));
        Tutor_Table.setRowHeight(25);
        
    }
    
    public StudentAfterLoginForm(String s_ID) {
        initComponents();
        show_teachers();
        
        Tutor_Table.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,12));
        Tutor_Table.getTableHeader().setOpaque(false);
        Tutor_Table.getTableHeader().setBackground(new Color(32, 136, 203));
        Tutor_Table.getTableHeader().setForeground(new Color(255,255,255));
        Tutor_Table.setRowHeight(25);
        textfield_s_code.setText(s_ID);
    }
    
    
    public ArrayList<Teacher> TeachersList(){
        
        ArrayList<Teacher> TeachersList = new ArrayList<>();
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=TuitionMedia100;selectMethod=cursor", "sa", "123456");
            
            String Query1 = "select t_Id, Name, Gender, Educational_Qualification, Area_Code from TEACHER";
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(Query1);
            
            //DefaultTableModel t_model = (DefaultTableModel)S_Table.getModel();
            //int selectedRowIndex = S_Table.getSelectedRow();
        
            //textfield_s_id.setText(t_model.getValueAt(selectedRowIndex, 0).toString());
            
            Teacher teacher;
            while(rs.next()){
                teacher = new Teacher(rs.getString("t_ID"),rs.getString("Name"),rs.getString("Gender"),rs.getString("Educational_Qualification"),rs.getInt("Area_Code"));
                TeachersList.add(teacher);
            }
            
            
            
            
            
        }
        
        catch(Exception e){
        
        System.out.println(e.getMessage());
        }return TeachersList;
    }
    
    public void show_teachers(){
        ArrayList<Teacher> list = TeachersList();
        DefaultTableModel t_model = (DefaultTableModel) Tutor_Table.getModel();
        Object [] row = new Object[7];
        
        for(int i = 0; i<list.size(); i++){
            
            row[0] = list.get(i).gett_Id();
            row[1] = list.get(i).getName();
            
            row[2] = list.get(i).getGender();
            row[3] = list.get(i).getEducational_Qualification();
            
            row[4] = list.get(i).getArea_Code();
            t_model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textfield_s_code = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textfield_t_code = new javax.swing.JTextField();
        request_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textfield_Postal_Code = new javax.swing.JTextField();
        Search_Teacher = new javax.swing.JButton();
        Search_Teacher1 = new javax.swing.JButton();
        Search_Teacher2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tutor_Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(74, 31, 61));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("   Tuition Media");

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("            Student");

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Code :");

        textfield_s_code.setEditable(false);
        textfield_s_code.setBackground(new java.awt.Color(74, 31, 61));
        textfield_s_code.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        textfield_s_code.setForeground(new java.awt.Color(255, 255, 255));
        textfield_s_code.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" ID                  :");

        textfield_t_code.setEditable(false);
        textfield_t_code.setBackground(new java.awt.Color(74, 31, 61));
        textfield_t_code.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        textfield_t_code.setForeground(new java.awt.Color(255, 255, 255));
        textfield_t_code.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        request_btn.setBackground(new java.awt.Color(0, 102, 102));
        request_btn.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        request_btn.setForeground(new java.awt.Color(255, 255, 255));
        request_btn.setText("Request");
        request_btn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        request_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                request_btnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Search using Postal :");

        textfield_Postal_Code.setBackground(new java.awt.Color(74, 31, 61));
        textfield_Postal_Code.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        textfield_Postal_Code.setForeground(new java.awt.Color(255, 255, 255));
        textfield_Postal_Code.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Search_Teacher.setBackground(new java.awt.Color(0, 102, 102));
        Search_Teacher.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        Search_Teacher.setForeground(new java.awt.Color(255, 255, 255));
        Search_Teacher.setText("Search");
        Search_Teacher.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Search_Teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_TeacherActionPerformed(evt);
            }
        });

        Search_Teacher1.setBackground(new java.awt.Color(0, 102, 102));
        Search_Teacher1.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        Search_Teacher1.setForeground(new java.awt.Color(255, 255, 255));
        Search_Teacher1.setText("Refresh");
        Search_Teacher1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Search_Teacher1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_Teacher1ActionPerformed(evt);
            }
        });

        Search_Teacher2.setBackground(new java.awt.Color(0, 102, 102));
        Search_Teacher2.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        Search_Teacher2.setForeground(new java.awt.Color(255, 255, 255));
        Search_Teacher2.setText("Log Out");
        Search_Teacher2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Search_Teacher2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_Teacher2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(textfield_t_code))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(textfield_s_code))))
                        .addGap(60, 60, 60))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(Search_Teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Search_Teacher1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Search_Teacher2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textfield_Postal_Code)))
                        .addGap(51, 51, 51))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(request_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_s_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_t_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(request_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_Postal_Code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Search_Teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search_Teacher1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_Teacher2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("                            Available Tutors :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
        );

        Tutor_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Gender", "Educational Qualification", "Postal Code"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tutor_Table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        Tutor_Table.setSelectionBackground(new java.awt.Color(0, 102, 102));
        Tutor_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tutor_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tutor_Table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Search_TeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_TeacherActionPerformed
        // TODO add your handling code here:
        /*DefaultTableModel  table=(DefaultTableModel)Tutor_Table.getModel();
        String search= textfield_Postal_Code.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table) ;
        Tutor_Table.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));*/
        DefaultTableModel dm = (DefaultTableModel)Tutor_Table.getModel();
        int rowCount = dm.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
        
        
        try{
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con= DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=TuitionMedia100;selectMethod=cursor", "sa", "123456");
            String id= textfield_Postal_Code.getText();
             
           
            Statement statement = con.createStatement();
            ResultSet resultSet = statement.executeQuery("select t_Id, Name, Gender, Educational_Qualification, Area_Code from TEACHER where Area_Code = '"+id+"' ");
            if (resultSet.next()){
                PreparedStatement ps= con.prepareStatement("select t_Id, Name, Gender, Educational_Qualification, Area_Code from TEACHER where Area_Code = '"+id+"' ");
                ResultSet rs=ps.executeQuery();
                DefaultTableModel tm;
              tm = (DefaultTableModel)Tutor_Table.getModel();
              
              while(rs.next()){
                   String e_name =rs.getString("t_Id");
                    String e_address=rs.getString("Name");
                    String salary =rs.getString("Gender");
                     String Educational_Qualification =rs.getString("Educational_Qualification");
                     String areacode =rs.getString("Area_Code");
                    Object o[]={rs.getString("t_Id"),rs.getString("Name"),rs.getString("Gender"),rs.getString("Educational_Qualification"),rs.getString("Area_Code")};
                  tm.addRow(o);
               }
            }
            else
            {
                 JOptionPane.showMessageDialog(this, "Not Found");
            }
            con.close();
         }catch (Exception e) {
            e.printStackTrace();
         }
        
        
        
        
        
        
    }//GEN-LAST:event_Search_TeacherActionPerformed

    private void request_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_request_btnActionPerformed
        // TODO add your handling code here:
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=TuitionMedia100;selectMethod=cursor", "sa", "123456");
            String Query = "INSERT INTO REQUESTED_TUTION(s_ID,t_ID) values(?, ?)";
            PreparedStatement pst = connection.prepareStatement(Query);
            pst.setString(1,textfield_s_code.getText());
            pst.setString(2,textfield_t_code.getText());
            
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Request Sent Successfull");
            
        }catch(Exception e){

            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_request_btnActionPerformed

    private void Tutor_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tutor_TableMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel t_model = (DefaultTableModel)Tutor_Table.getModel();
        int selectedRowIndex = Tutor_Table.getSelectedRow();
        
        textfield_t_code.setText(t_model.getValueAt(selectedRowIndex, 0).toString());
    }//GEN-LAST:event_Tutor_TableMouseClicked

    private void Search_Teacher1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_Teacher1ActionPerformed
        // TODO add your handling code here:
        show_teachers();
    }//GEN-LAST:event_Search_Teacher1ActionPerformed

    private void Search_Teacher2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_Teacher2ActionPerformed
        // TODO add your handling code here:
        StudentLoginForm s = new StudentLoginForm();
        s.show();
        dispose();
    }//GEN-LAST:event_Search_Teacher2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentAfterLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentAfterLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentAfterLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentAfterLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentAfterLoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Register_Back;
    private javax.swing.JButton Search_Teacher;
    private javax.swing.JButton Search_Teacher1;
    private javax.swing.JButton Search_Teacher2;
    private javax.swing.JTable Tutor_Table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton request_btn;
    private javax.swing.JTextField textfield_Postal_Code;
    private javax.swing.JTextField textfield_s_code;
    private javax.swing.JTextField textfield_t_code;
    // End of variables declaration//GEN-END:variables
}
