/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tutuionmediapleaseletitbefinal;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author blank
 */
public class TeacherJobBoard extends javax.swing.JFrame {

    /**
     * Creates new form TeacherJobBoard
     */
    public TeacherJobBoard() {
        initComponents();
        show_students();
        
        S_Table.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,12));
        S_Table.getTableHeader().setOpaque(false);
        S_Table.getTableHeader().setBackground(new Color(32, 136, 203));
        S_Table.getTableHeader().setForeground(new Color(255,255,255));
        S_Table.setRowHeight(25);
    }
    
    public TeacherJobBoard(String t_ID){
        initComponents();
        show_students();
        
        S_Table.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,12));
        S_Table.getTableHeader().setOpaque(false);
        S_Table.getTableHeader().setBackground(new Color(32, 136, 203));
        S_Table.getTableHeader().setForeground(new Color(255,255,255));
        S_Table.setRowHeight(25);
        textfield_teacher_code.setText(t_ID);
        
        //DefaultTableModel t_model = (DefaultTableModel)S_Table.getModel();
        //int selectedRowIndex = S_Table.getSelectedRow();
        
        //textfield_s_id.setText(t_model.getValueAt(selectedRowIndex, 0).toString());
        
    }

    
    public ArrayList<Student> StudentsList(){
        
        ArrayList<Student> StudentsList = new ArrayList<>();
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=TuitionMedia100;selectMethod=cursor", "sa", "123456");
            
            String Query1 = "select s_Id, Name, Age, Gender, Educational_Institution, Class, Medium_Version from STUDENT ";
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(Query1);
            
            //DefaultTableModel t_model = (DefaultTableModel)S_Table.getModel();
            //int selectedRowIndex = S_Table.getSelectedRow();
        
            //textfield_s_id.setText(t_model.getValueAt(selectedRowIndex, 0).toString());
            
            Student student;
            while(rs.next()){
                student = new Student(rs.getString("s_ID"),rs.getString("Name"),rs.getInt("Age"),rs.getString("Gender"),rs.getString("Educational_Institution"),rs.getString("Class"),rs.getString("Medium_Version"));
                StudentsList.add(student);
            }
            
            //DefaultTableModel t_model = (DefaultTableModel)S_Table.getModel();
            //int selectedRowIndex = S_Table.getSelectedRow();
        
            //textfield_s_id.setText(t_model.getValueAt(selectedRowIndex, 0).toString());
            
            
            
        }
        
        catch(Exception e){
        
        System.out.println(e.getMessage());
        }return StudentsList;
    }
    
    
    public void show_students(){
        ArrayList<Student> list = StudentsList();
        DefaultTableModel t_model = (DefaultTableModel) S_Table.getModel();
        Object [] row = new Object[7];
        
        for(int i = 0; i<list.size(); i++){
            
            row[0] = list.get(i).gets_Id();
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getAge();
            row[3] = list.get(i).getGender();
            row[4] = list.get(i).getEducational_Institution();
            row[5] = list.get(i).getStudentClass();
            row[6] = list.get(i).getMedium_Version();
            t_model.addRow(row);
        }
        
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textfield_teacher_code = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textfield_s_id = new javax.swing.JTextField();
        apply_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textfield_Class = new javax.swing.JTextField();
        teachersearch = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        logout_btn1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        S_Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(74, 31, 61));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("   Tuition Media");

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("             Teacher");

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Teacher Code :");

        textfield_teacher_code.setEditable(false);
        textfield_teacher_code.setBackground(new java.awt.Color(74, 31, 61));
        textfield_teacher_code.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        textfield_teacher_code.setForeground(new java.awt.Color(255, 255, 255));
        textfield_teacher_code.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" ID                :");

        textfield_s_id.setEditable(false);
        textfield_s_id.setBackground(new java.awt.Color(74, 31, 61));
        textfield_s_id.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        textfield_s_id.setForeground(new java.awt.Color(255, 255, 255));
        textfield_s_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        apply_btn.setBackground(new java.awt.Color(0, 102, 102));
        apply_btn.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        apply_btn.setForeground(new java.awt.Color(255, 255, 255));
        apply_btn.setText("Apply");
        apply_btn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        apply_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apply_btnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Search using class :");

        textfield_Class.setBackground(new java.awt.Color(74, 31, 61));
        textfield_Class.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        textfield_Class.setForeground(new java.awt.Color(255, 255, 255));
        textfield_Class.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        teachersearch.setBackground(new java.awt.Color(0, 102, 102));
        teachersearch.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        teachersearch.setForeground(new java.awt.Color(255, 255, 255));
        teachersearch.setText("Search");
        teachersearch.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        teachersearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachersearchActionPerformed(evt);
            }
        });

        logout_btn.setBackground(new java.awt.Color(0, 102, 102));
        logout_btn.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(255, 255, 255));
        logout_btn.setText("Log Out");
        logout_btn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });

        logout_btn1.setBackground(new java.awt.Color(0, 102, 102));
        logout_btn1.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        logout_btn1.setForeground(new java.awt.Color(255, 255, 255));
        logout_btn1.setText("Refresh");
        logout_btn1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        logout_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(textfield_s_id))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(textfield_teacher_code))))
                        .addGap(60, 60, 60))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(teachersearch, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(logout_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textfield_Class)))
                        .addGap(51, 51, 51))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(apply_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_teacher_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_s_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(apply_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_Class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teachersearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(186, 34, 81));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 45)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("                         Available Tuitions:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        S_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Age", "Gender", "Instituition", "Class", "Version/Medium"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        S_Table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        S_Table.setRowHeight(25);
        S_Table.setSelectionBackground(new java.awt.Color(232, 57, 95));
        S_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(S_Table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apply_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apply_btnActionPerformed
        // TODO add your handling code here:
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=TuitionMedia100;selectMethod=cursor", "sa", "123456");
            String Query = "INSERT INTO APPLIED_TUITION(t_ID,s_ID) values(?, ?)";
            PreparedStatement pst = connection.prepareStatement(Query);
            pst.setString(1,textfield_teacher_code.getText());
            pst.setString(2,textfield_s_id.getText());
            
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Applying Successfull");
            
        }catch(Exception e){

            System.out.println(e.getMessage());
        }
        

        
    }//GEN-LAST:event_apply_btnActionPerformed

    private void teachersearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachersearchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel)S_Table.getModel();
        int rowCount = dm.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
        
        
        try{
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con= DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=TuitionMedia100;selectMethod=cursor", "sa", "123456");
            String id= textfield_Class.getText();
             
           
            Statement statement = con.createStatement();
            ResultSet resultSet = statement.executeQuery("select s_Id, Name, Age, Gender, Educational_Institution, Class, Medium_Version from STUDENT where Class = '"+id+"' ");
            if (resultSet.next()){
                PreparedStatement ps= con.prepareStatement("select s_Id, Name, Age, Gender, Educational_Institution, Class, Medium_Version from STUDENT where Class = '"+id+"' ");
                ResultSet rs=ps.executeQuery();
                DefaultTableModel tm;
              tm = (DefaultTableModel)S_Table.getModel();
              
              while(rs.next()){
                   String e_name =rs.getString("s_Id");
                    String e_address=rs.getString("Name");
                    String e_age=rs.getString("Age");
                    String salary =rs.getString("Gender");
                     String Educational_Qualification =rs.getString("Educational_Institution");
                     String student_class=rs.getString("Class");
                     String areacode =rs.getString("Medium_Version");
                    Object o[]={rs.getString("s_Id"),rs.getString("Name"),rs.getString("Age"),rs.getString("Gender"),rs.getString("Educational_Institution"),rs.getString("Class"),rs.getString("Medium_Version")};
                  tm.addRow(o);
               }
            }
            else
            {
                 JOptionPane.showMessageDialog(this, "INVALID!!");
            }
            con.close();
         }catch (Exception e) {
            e.printStackTrace();
         }
    }//GEN-LAST:event_teachersearchActionPerformed

    private void S_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_TableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel t_model = (DefaultTableModel)S_Table.getModel();
        int selectedRowIndex = S_Table.getSelectedRow();
        
        textfield_s_id.setText(t_model.getValueAt(selectedRowIndex, 0).toString());
        
    }//GEN-LAST:event_S_TableMouseClicked

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        // TODO add your handling code here:
        
        TeacherLoginForm t = new TeacherLoginForm();
        t.show();
        
        dispose();
    }//GEN-LAST:event_logout_btnActionPerformed

    private void logout_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btn1ActionPerformed
        // TODO add your handling code here:
        show_students();
        
    }//GEN-LAST:event_logout_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherJobBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherJobBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherJobBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherJobBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherJobBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable S_Table;
    private javax.swing.JButton apply_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton logout_btn1;
    private javax.swing.JButton teachersearch;
    private javax.swing.JTextField textfield_Class;
    private javax.swing.JTextField textfield_s_id;
    private javax.swing.JTextField textfield_teacher_code;
    // End of variables declaration//GEN-END:variables
}
